In [1]:
import tensorflow as tf
import numpy as np

In [4]:
xvals = np.array([_ for _ in range(1, 11, 2)])

In [5]:
xdata = tf.Variable(xvals, dtype = 'float32')
mconst= tf.constant(3.)
operation = tf.multiply(xdata, mconst)
print(operation.numpy())

[ 3.  9. 15. 21. 27.]


In [6]:
# 2. Layering Operations

myArray = np.array([[_ for _ in range(1,11,2)],
                    [_ for _ in range(-2, 8, 2)],
                    [_ for _ in range(-6, 9, 3)]])

In [7]:
xvals   = np.array([myArray, myArray + 1])
xdata   = tf.Variable(xvals, dtype = tf.float32)

In [8]:
m1 = tf.constant([[1.],[0.0],[-1.],[2.],[4.]])
m2 = tf.constant([[2.]])
a1 = tf.constant([[10.]])

def prod1(a,b):
    result = tf.matmul(a,b)
    return result

def prod2(a,b):
    return tf.matmul(a,b)

def add1(a,b):
    return tf.add(a,b)

In [10]:
result = add1(prod2(prod1(xdata, m1),m2),a1)

print(result.numpy())

[[[102.]
  [ 66.]
  [ 58.]]

 [[114.]
  [ 78.]
  [ 70.]]]


In [11]:
# 3. Classing all the operations
class Operation():
    def __init__(self, result):
        self.result = result
        
    def call1(self, func, a_const):
        self.result = func(self.result, a_const)
        return self
    

In [12]:
operations = Operation(result = xdata).call1(prod1, m1).call1(prod2,m2).call1(add1, a1)

In [13]:
print(operations.result.numpy())

[[[102.]
  [ 66.]
  [ 58.]]

 [[114.]
  [ 78.]
  [ 70.]]]


In [14]:
# working with multiple layers
import tensorflow as tf
import numpy as np

batch_size = [1]
xshape     = [4,4,1]
xdata      = tf.random.normal(shape = batch_size + xshape)

In [21]:
# creating the first layer
def first_layer(x):
    myFilter = tf.constant(0.25, shape = [2,2,1,1])
    myStrides= [1,2,2,1]
    layer = tf.nn.conv2d(x, myFilter, myStrides,padding = 'SAME', name = 'moving_average_layer')
    return layer

In [22]:
# creating the second layer
def second_layer(x):
    # squeeze the dimensions of the input image
    x_s = tf.squeeze(x)
    A = tf.constant([[1.,2.],[-1.,3.]])
    b = tf.constant(1., shape = [2,2])
    result = tf.matmul(A, x_s)
    result = tf.add(result, b)
    return tf.sigmoid(result)

In [23]:
first_layer_tensor = first_layer(xdata)
second_layer_tensor= second_layer(first_layer_tensor)

print(second_layer_tensor.numpy())

[[0.6436587  0.23613526]
 [0.6168212  0.39793158]]


In [24]:
# Implementing Loss Functions

import matplotlib.pyplot as plt
import tensorflow as tf

In [25]:
xvals = tf.linspace(-1., 1., 500)
target= tf.constant(0.)

In [1]:
# Regression based loss functions
# L2 Loss

def l2(y, yp):
    return tf.square(y-yp)

# L1 loss
def l1(y, yp):
    return tf.abs(y-yp)

# pseudo-huber loss
def phuber1(y, yp):
    delta1 = tf.constant(0.25)
    loss   = tf.multiply(delta1, tf.sqrt(1 + tf.square((y-yp)/delta1)) - 1.)
    return loss

def phuber2(y, yp):
    delta2 = tf.constant(5)
    loss   = tf.multiply(delta2, tf.sqrt(1 + tf.square((y-yp)/delta2)) - 1.)