In [1]:
import tensorflow as tf


In [3]:
tf.executing_eagerly()

True

In [7]:
x = [[2.]]
a = tf.matmul(x,x)
print("The result is {}".format(a))


The result is [[4.]]


In [11]:
a = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]], dtype = 'float32')

In [18]:
b = tf.ones([3,3], dtype = 'float32')
b = tf.linalg.diag([1., 1., 1.])

In [19]:
c = tf.matmul(a,b)

In [20]:
print(c)

tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]], shape=(1, 3, 3), dtype=float32)


In [28]:
d1 = tf.random.uniform([3,3], minval = 0, maxval = 10, dtype = tf.int32)
print(d1)

tf.Tensor(
[[7 4 9]
 [2 6 9]
 [8 1 9]], shape=(3, 3), dtype=int32)


In [33]:
d2 = tf.random.truncated_normal([3,3], mean = 0., stddev = 1.)
print(d2)

tf.Tensor(
[[-0.81196487  0.14279208  0.22044052]
 [-0.42362154 -1.1251493  -1.182508  ]
 [ 1.4829593   1.1007762   0.96233577]], shape=(3, 3), dtype=float32)


In [39]:
e = tf.range(1, 10, 2)
e = tf.random.shuffle(e)

In [40]:
print(e)

tf.Tensor([5 1 3 9 7], shape=(5,), dtype=int32)


In [41]:
import numpy as np

In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
a.dtype

dtype('int32')

In [47]:
b = tf.convert_to_tensor(a)

In [48]:
print(b)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [57]:
import tensorflow as tf

In [61]:
print(c - c)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


In [64]:
f = tf.math.divide(3,3)

In [65]:
print(f)

tf.Tensor(1.0, shape=(), dtype=float64)


In [68]:
print(tf.math.divide(3,4))

tf.Tensor(0.75, shape=(), dtype=float64)


In [81]:
a = tf.math.abs(tf.random.uniform([3,3], minval = -10, maxval = 10, dtype = tf.int32))
print(a)

tf.Tensor(
[[ 0  3  7]
 [ 4  4  9]
 [ 3  2 10]], shape=(3, 3), dtype=int32)


In [82]:
print(tf.math.mod(a, 3))

tf.Tensor(
[[0 0 1]
 [1 1 0]
 [0 2 1]], shape=(3, 3), dtype=int32)


In [84]:
w = tf.nn.relu([-3,3,10])

In [87]:
[_ for _ in range(1,10,2)]

[1, 3, 5, 7, 9]

In [88]:
a = np.array([[_ for _ in range(1,10,2)],[_ for _ in range(-2,8,2)],[_ for _ in range(-6,9,3)]])

In [91]:
xvals = np.array([a, a+1])

In [92]:
xdata = tf.Variable(xvals, dtype = tf.float32)

In [94]:
# now you want to create a 5 x 1
m1 = tf.constant([[1.],[0.],[-1.],[2.],[4.]])
# constant tensor of size 1 x 1
m2 = tf.constant([[2.]])
# constant tensor of size 1 x 1
a1 = tf.constant([[10.]])

In [99]:
def prod1(a,b):
    return tf.matmul(a,b)

def prod2(a,b):
    return tf.matmul(a,b)

def add1(a,b):
    return tf.add(a,b)

In [100]:
result = add1(prod2(prod1(xdata,m1), m2),a1)

In [103]:
print(result.numpy())

[[[102.]
  [ 66.]
  [ 58.]]

 [[114.]
  [ 78.]
  [ 70.]]]


In [145]:
class Operations():
    def __init__(self, a):
        self.result = a
    
    def apply(self, func, b):
        self.result = func(self.result,b)    
        return self



In [146]:
operation = Operations(a = xdata)

In [147]:
operation.apply(prod1, m1).apply(prod2,m2).apply(add1, a1)

In [149]:
print(operation.result.numpy())

[[[102.]
  [ 66.]
  [ 58.]]

 [[114.]
  [ 78.]
  [ 70.]]]


In [1]:
# Working with Multiple Layers
import tensorflow as tf
import numpy as np

In [5]:
batch_size = [1]
img_size   = [4,4,1]
xval = tf.random.uniform(shape = batch_size + img_size)

In [22]:
# developing the first layer
def moving_avg(x):
    myFilter = tf.constant([[[[0.25]],[[0.25]]],[[[0.25]],[[0.25]]]], dtype = tf.float32)
    myStrides= [1,2,2,1]
    return tf.nn.conv2d(x, myFilter, myStrides, padding = 'SAME', name = 'moving_avg_layer')

In [23]:
# developing the second layer
def second_layer(x):
    # first would have to squeeze the input into a 2Dim matrix from a 4 Dim
    x = tf.squeeze(x)
    A = tf.constant([[1,2],[-1,4]], dtype = tf.float32)
    b = tf.constant(1., shape = (2,2))
    return tf.nn.sigmoid(tf.add(tf.matmul(A,x),b))

In [24]:
first_layer_tensor  = moving_avg(xval)
second_layer_tensor = second_layer(first_layer_tensor)
print(second_layer_tensor.numpy())

[[0.89600694 0.7882971 ]
 [0.8939904  0.7705411 ]]


In [28]:
np.median(np.array([18, 6, 12, 10, 15]))

12.0

In [30]:
np.mean([4,6,7,9,2000000])

400005.2